In [ ]:
import os
import pandas as pd
import numpy as np
import pyspark
from pyspark.sql import SparkSession

In [ ]:
spark = SparkSession.builder.appName("OlistDataAnalysis").getOrCreate()
print("SparkSession initialized.")

olist_pd_orders_cleaned_df = spark.read.csv('/content/olist_orders_cleaned.csv', header=True, inferSchema=True)
print('olist_orders_cleaned loaded.')

SparkSession initialized.
olist_orders_cleaned loaded.

### Limpeza e Análise com Pandas: `olist_orders_dataset.csv`

In [ ]:
# Carregar o dataset principal com pandas
pd_orders_df = pd.read_csv('/content/olist_orders_dataset.csv')

print('Primeiras 5 linhas do DataFrame:')
display(pd_orders_df.head())

print('\nInformações do DataFrame (incluindo tipos de dados e valores não nulos):')
display(pd_orders_df.info())

print('\nContagem de valores nulos por coluna:')
display(pd_orders_df.isnull().sum())

Primeiras 5 linhas do DataFrame:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

Informações do DataFrame (incluindo tipos de dados e valores não nulos):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

None

Contagem de valores nulos por coluna:

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

### Script de Limpeza de Dados com Pandas (Exemplo para `olist_orders_dataset.csv`)

Vamos converter as colunas de data para o tipo datetime e, para fins de demonstração, preencher os valores nulos das datas de aprovação e entrega com uma estratégia simples (por exemplo, preenchendo com a data de compra mais um delta).

In [ ]:
pd_orders_cleaned_df = pd_orders_df.copy()

# Converter colunas de timestamp para datetime
date_cols_pd = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col_name in date_cols_pd:
    pd_orders_cleaned_df[col_name] = pd.to_datetime(pd_orders_cleaned_df[col_name])

# Preencher valores nulos para 'order_approved_at'
# Se 'order_approved_at' for nulo, preencher com
# 'order_purchase_timestamp' + 1 dia
pd_orders_cleaned_df['order_approved_at'] = pd_orders_cleaned_df['order_approved_at'].fillna(
    pd_orders_cleaned_df['order_purchase_timestamp'] + pd.Timedelta(days=1)
)

# Preencher valores nulos para 'order_delivered_carrier_date'
# Se 'order_delivered_carrier_date' for nulo, preencher com
#'order_approved_at' + 1 dia
pd_orders_cleaned_df['order_delivered_carrier_date'] = pd_orders_cleaned_df['order_delivered_carrier_date'].fillna(
    pd_orders_cleaned_df['order_approved_at'] + pd.Timedelta(days=1)
)

# Preencher valores nulos para 'order_delivered_customer_date'
# Se 'order_delivered_customer_date' for nulo, preencher com
#'order_delivered_carrier_date' + 2 dias
pd_orders_cleaned_df['order_delivered_customer_date'] = pd_orders_cleaned_df['order_delivered_customer_date'].fillna(
    pd_orders_cleaned_df['order_delivered_carrier_date'] + pd.Timedelta(days=2)
)

print('DataFrame pandas após limpeza básica:')
display(pd_orders_cleaned_df.head())

print('\nContagem de valores nulos após limpeza:')
display(pd_orders_cleaned_df.isnull().sum())

pd_orders_cleaned_df.to_csv('olist_orders_cleaned.csv', index=False)

DataFrame pandas após limpeza básica:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

Contagem de valores nulos após limpeza:

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64

### PySpark SQL: Olhar a tabela limpa e seus tipos

In [ ]:
# Registrar todos os DataFrames PySpark como tabelas temporárias para SQL
olist_pd_orders_cleaned_df.createOrReplaceTempView("orders")
print("Tabelas temporárias PySpark SQL criadas.")

# Query para listar todas as tabelas e seus esquemas
all_tables = spark.catalog.listTables()

for table in all_tables:
    if table.isTemporary:
        print(f"\n--- Esquema da Tabela '{table.name}' ---")
        spark.sql(f"DESCRIBE {table.name}").show()

print("\nPrimeiras 5 linhas da Tabela 'orders_cleaned' (após limpeza) para verificar os dados:")
spark.sql("SELECT * FROM orders LIMIT 5").show()

Tabelas temporárias PySpark SQL criadas.

--- Esquema da Tabela 'category_translation' ---
+--------------------+---------+-------+
|            col_name|data_type|comment|
+--------------------+---------+-------+
|product_category_...|   string|   NULL|
|product_category_...|   string|   NULL|
+--------------------+---------+-------+


--- Esquema da Tabela 'customers' ---
+--------------------+---------+-------+
|            col_name|data_type|comment|
+--------------------+---------+-------+
|         customer_id|   string|   NULL|
|  customer_unique_id|   string|   NULL|
|customer_zip_code...|      int|   NULL|
|       customer_city|   string|   NULL|
|      customer_state|   string|   NULL|
+--------------------+---------+-------+


--- Esquema da Tabela 'geolocation' ---
+--------------------+---------+-------+
|            col_name|data_type|comment|
+--------------------+---------+-------+
|geolocation_zip_c...|      int|   NULL|
|     geolocation_lat|   double|   NULL|
|     geolocation_lng|   double|   NULL|
|    geolocation_city|   string|   NULL|
|   geolocation_state|   string|   NULL|
+--------------------+---------+-------+


--- Esquema da Tabela 'order_items' ---
+-------------------+---------+-------+
|           col_name|data_type|comment|
+-------------------+---------+-------+
|           order_id|   string|   NULL|
|      order_item_id|      int|   NULL|
|         product_id|   string|   NULL|
|          seller_id|   string|   NULL|
|shipping_limit_date|timestamp|   NULL|
|              price|   double|   NULL|
|      freight_value|   double|   NULL|
+-------------------+---------+-------+


--- Esquema da Tabela 'order_payments' ---
+--------------------+---------+-------+
|            col_name|data_type|comment|
+--------------------+---------+-------+
|            order_id|   string|   NULL|
|  payment_sequential|      int|   NULL|
|        payment_type|   string|   NULL|
|payment_installments|      int|   NULL|
|       payment_value|   double|   NULL|
+--------------------+---------+-------+


--- Esquema da Tabela 'order_reviews' ---
+--------------------+---------+-------+
|            col_name|data_type|comment|
+--------------------+---------+-------+
|           review_id|   string|   NULL|
|            order_id|   string|   NULL|
|        review_score|   string|   NULL|
|review_comment_title|   string|   NULL|
|review_comment_me...|   string|   NULL|
|review_creation_date|   string|   NULL|
|review_answer_tim...|   string|   NULL|
+--------------------+---------+-------+


--- Esquema da Tabela 'orders' ---
+--------------------+---------+-------+
|            col_name|data_type|comment|
+--------------------+---------+-------+
|            order_id|   string|   NULL|
|         customer_id|   string|   NULL|
|        order_status|   string|   NULL|
|order_purchase_ti...|timestamp|   NULL|
|   order_approved_at|timestamp|   NULL|
|order_delivered_c...|timestamp|   NULL|
|order_delivered_c...|timestamp|   NULL|
|order_estimated_d...|     date|   NULL|
+--------------------+---------+-------+


--- Esquema da Tabela 'orders_initial' ---
+--------------------+---------+-------+
|            col_name|data_type|comment|
+--------------------+---------+-------+
|            order_id|   string|   NULL|
|         customer_id|   string|   NULL|
|        order_status|   string|   NULL|
|order_purchase_ti...|timestamp|   NULL|
|   order_approved_at|timestamp|   NULL|
|order_delivered_c...|timestamp|   NULL|
|order_delivered_c...|timestamp|   NULL|
|order_estimated_d...|timestamp|   NULL|
+--------------------+---------+-------+


--- Esquema da Tabela 'products' ---
+--------------------+---------+-------+
|            col_name|data_type|comment|
+--------------------+---------+-------+
|          product_id|   string|   NULL|
|product_category_...|   string|   NULL|
| product_name_lenght|      int|   NULL|
|product_descripti...|      int|   NULL|
|  product_photos_qty|      int|   NULL|
|    product_weight_g|      int|   NULL|
|   product_length_cm|      int|   NULL|
|   product_height_cm|      int|   NULL|
|    product_width_cm|      int|   NULL|
+--------------------+---------+-------+


--- Esquema da Tabela 'sellers' ---
+--------------------+---------+-------+
|            col_name|data_type|comment|
+--------------------+---------+-------+
|           seller_id|   string|   NULL|
|seller_zip_code_p...|      int|   NULL|
|         seller_city|   string|   NULL|
|        seller_state|   string|   NULL|
+--------------------+---------+-------+


Primeiras 5 linhas da Tabela 'orders_cleaned' (após limpeza) para verificar os dados:
+--------------------+--------------------+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+
|            order_id|         customer_id|order_status|order_purchase_timestamp|  order_approved_at|order_delivered_carrier_date|order_delivered_customer_date|order_estimated_delivery_date|
+--------------------+--------------------+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+
|e481f51cbdc54678b...|9ef432eb625129730...|   delivered|     2017-10-02 10:56:33|2017-10-02 11:07:15|         2017-10-04 19:55:00|          2017-10-10 21:25:13|                   2017-10-18|
|53cdb2fc8bc7dce0b...|b0830fb4747a6c6d2...|   delivered|     2018-07-24 20:41:37|2018-07-26 03:24:27|         2018-07-26 14:31:00|          2018-08-07 15:27:45|                   2018-08-13|
|47770eb9100c2d0c4...|41ce2a54c0b03bf34...|   delivered|     2018-08-08 08:38:49|2018-08-08 08:55:23|         2018-08-08 13:50:00|          2018-08-17 18:06:29|                   2018-09-04|
|949d5b44dbf5de918...|f88197465ea7920ad...|   delivered|     2017-11-18 19:28:06|2017-11-18 19:45:59|         2017-11-22 13:39:59|          2017-12-02 00:28:42|                   2017-12-15|
|ad21c59c0840e6cb8...|8ab97904e6daea886...|   delivered|     2018-02-13 21:18:39|2018-02-13 22:20:29|         2018-02-14 19:46:34|          2018-02-16 18:17:02|                   2018-02-26|
+--------------------+--------------------+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+

In [ ]:
spark.sql("""
SELECT
    order_status,
    order_purchase_timestamp,
    order_approved_at,
    order_delivered_carrier_date,
    order_delivered_customer_date,
    order_estimated_delivery_date
FROM orders
""").show()

+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+
|order_status|order_purchase_timestamp|  order_approved_at|order_delivered_carrier_date|order_delivered_customer_date|order_estimated_delivery_date|
+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+
|   delivered|     2017-10-02 10:56:33|2017-10-02 11:07:15|         2017-10-04 19:55:00|          2017-10-10 21:25:13|                   2017-10-18|
|   delivered|     2018-07-24 20:41:37|2018-07-26 03:24:27|         2018-07-26 14:31:00|          2018-08-07 15:27:45|                   2018-08-13|
|   delivered|     2018-08-08 08:38:49|2018-08-08 08:55:23|         2018-08-08 13:50:00|          2018-08-17 18:06:29|                   2018-09-04|
|   delivered|     2017-11-18 19:28:06|2017-11-18 19:45:59|         2017-11-22 13:39:59|          2017-12-02 00:28:42|                   2017-12-15|
|   delivered|     2018-02-13 21:18:39|2018-02-13 22:20:29|         2018-02-14 19:46:34|          2018-02-16 18:17:02|                   2018-02-26|
|   delivered|     2017-07-09 21:57:05|2017-07-09 22:10:13|         2017-07-11 14:58:04|          2017-07-26 10:57:55|                   2017-08-01|
|    invoiced|     2017-04-11 12:22:08|2017-04-13 13:25:17|         2017-04-14 13:25:17|          2017-04-16 13:25:17|                   2017-05-09|
|   delivered|     2017-05-16 13:10:30|2017-05-16 13:22:11|         2017-05-22 10:07:46|          2017-05-26 12:55:51|                   2017-06-07|
|   delivered|     2017-01-23 18:29:09|2017-01-25 02:50:47|         2017-01-26 14:16:31|          2017-02-02 14:08:10|                   2017-03-06|
|   delivered|     2017-07-29 11:55:02|2017-07-29 12:05:32|         2017-08-10 19:45:24|          2017-08-16 17:14:30|                   2017-08-23|
|   delivered|     2017-05-16 19:41:10|2017-05-16 19:50:18|         2017-05-18 11:40:40|          2017-05-29 11:18:31|                   2017-06-07|
|   delivered|     2017-07-13 19:58:11|2017-07-13 20:10:08|         2017-07-14 18:43:29|          2017-07-19 14:04:48|                   2017-08-08|
|   delivered|     2018-06-07 10:06:19|2018-06-09 03:13:12|         2018-06-11 13:29:00|          2018-06-19 12:05:52|                   2018-07-18|
|   delivered|     2018-07-25 17:44:10|2018-07-25 17:55:14|         2018-07-26 13:16:00|          2018-07-30 15:52:25|                   2018-08-08|
|   delivered|     2018-03-01 14:14:28|2018-03-01 15:10:47|         2018-03-02 21:09:20|          2018-03-12 23:36:26|                   2018-03-21|
|   delivered|     2018-06-07 19:03:12|2018-06-12 23:31:02|         2018-06-11 14:54:00|          2018-06-21 15:34:32|                   2018-07-04|
|   delivered|     2018-01-02 19:00:43|2018-01-02 19:09:04|         2018-01-03 18:19:09|          2018-01-20 01:38:59|                   2018-02-06|
|   delivered|     2017-12-26 23:41:31|2017-12-26 23:50:22|         2017-12-28 18:33:05|          2018-01-08 22:36:36|                   2018-01-29|
|   delivered|     2017-11-21 00:03:41|2017-11-21 00:14:22|         2017-11-23 21:32:26|          2017-11-27 18:28:00|                   2017-12-11|
|   delivered|     2017-10-26 15:54:26|2017-10-26 16:08:14|         2017-10-26 21:46:53|          2017-11-08 22:22:00|                   2017-11-23|
+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+
only showing top 20 rows